server:
  port: 8011

spring:
  datasource:
    url: jdbc:mysql://10.0.181.204:13306/bs_exp_vue?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ZHTKFc5ta7tPTeyx
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

app:
  file:
    upload-dir: D:\bs_exp_vue\tomcat6\webapps\ROOT\uploads
    url-prefix: http://10.0.181.203:8080/uploads
  minio:
    endpoint: http://10.0.181.204:19000
    access-key: minio
    secret-key: KCfK6d2e7JkJWkEp
    bucket: bslab-media-dev
    url-prefix: http://10.0.181.204:19000/bslab-media-dev
    max-file-size: 1048576000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
