# ===========================
# 开发环境配置 (dev)
# 激活方式：--spring.profiles.active=dev
# ===========================
server:
  port: 8010

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  dingtalk:
    enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
